import type { BoardTicket } from "@/types/board";
import { minutesAgo } from "@/utils/minutes-ago";

export const DEMO_TICKETS: BoardTicket[] = [
  {
    id: "demo-1",
    subject: "Cannot access billing settings",
    body: "I upgraded the plan but my admin account still cannot access billing settings. It shows a permissions error.",
    status: "received",
    priority: "high",
    customerEmail: "maya@acme.com",
    workflowRunId: null,
    approvalEventId: null,
    createdAt: minutesAgo(8),
    summary: "Admin sees a permissions error after plan upgrade.",
    classification: null,
    draftResponse: null,
    resolution: null,
  },
  {
    id: "demo-2",
    subject: "Invoice export missing rows",
    body: "The May invoice CSV export is missing two team invoices. Can you help us reconcile the report?",
    status: "received",
    priority: "normal",
    customerEmail: "jon@bell.io",
    workflowRunId: null,
    approvalEventId: null,
    createdAt: minutesAgo(23),
    summary: "CSV export excludes two team invoices from May.",
    classification: null,
    draftResponse: null,
    resolution: null,
  },
  {
    id: "demo-3",
    subject: "Webhook retries are delayed",
    body: "Our production integration is waiting on webhook retries and customer provisioning is blocked.",
    status: "triaging",
    priority: "urgent",
    customerEmail: "priya@shah.dev",
    workflowRunId: null,
    approvalEventId: null,
    createdAt: minutesAgo(34),
    summary: "Production integration is waiting on retry delivery.",
    classification: null,
    draftResponse: null,
    resolution: null,
  },
  {
    id: "demo-4",
    subject: "Need help changing account owner",
    body: "We need to transfer account ownership to a new admin. Please confirm the steps before we proceed.",
    status: "drafted",
    priority: "low",
    customerEmail: "erik@novak.se",
    workflowRunId: null,
    approvalEventId: null,
    createdAt: minutesAgo(62),
    summary: "Requester needs the ownership transfer steps confirmed.",
    classification: {
      category: "general",
      sentiment: "neutral",
      confidence: 0.58,
      needsHumanApproval: false,
      summary: "Ticket can likely be answered with a standard support response.",
    },
    draftResponse:
      "Hi, thanks for reaching out about \"Need help changing account owner\".\n\nI categorized this as general and summarized it as: Ticket can likely be answered with a standard support response.\n\nHere is the recommended next step: we will review the account details and follow up with a concrete resolution shortly.\n\nThanks for your patience.",
    resolution: null,
  },
  {
    id: "demo-5",
    subject: "Data retention concern",
    body: "A customer is asking whether we can delete retained data earlier than our default retention period.",
    status: "waiting_for_approval",
    priority: "high",
    customerEmail: "nora@alvarez.com",
    workflowRunId: null,
    approvalEventId: null,
    createdAt: minutesAgo(120),
    summary: "Draft response is ready but needs policy review.",
    classification: {
      category: "general",
      sentiment: "negative",
      confidence: 0.78,
      needsHumanApproval: true,
      summary: "Customer appears blocked and needs fast human attention.",
    },
    draftResponse:
      "Hi, thanks for reaching out about \"Data retention concern\".\n\nI categorized this as general and summarized it as: Customer appears blocked and needs fast human attention.\n\nI am routing this to a teammate for review before sending a final reply.\n\nThanks for your patience.",
    resolution: null,
  },
  {
    id: "demo-6",
    subject: "Escalation request for outage report",
    body: "The customer is requesting a formal incident summary for last night's outage and wants an ETA.",
    status: "waiting_for_approval",
    priority: "urgent",
    customerEmail: "support@acme.com",
    workflowRunId: null,
    approvalEventId: null,
    createdAt: minutesAgo(180),
    summary: "Customer is asking for a formal incident summary.",
    classification: {
      category: "technical",
      sentiment: "neutral",
      confidence: 0.78,
      needsHumanApproval: true,
      summary: "Customer appears blocked and needs fast human attention.",
    },
    draftResponse:
      "Hi, thanks for reaching out about \"Escalation request for outage report\".\n\nI categorized this as technical and summarized it as: Customer appears blocked and needs fast human attention.\n\nI am routing this to a teammate for review before sending a final reply.\n\nThanks for your patience.",
    resolution: null,
  },
  {
    id: "demo-7",
    subject: "API key rotation question",
    body: "Can you share the recommended API key rotation process for our production workspace?",
    status: "resolved",
    priority: "normal",
    customerEmail: "lena@ortiz.mx",
    workflowRunId: null,
    approvalEventId: null,
    createdAt: minutesAgo(240),
    summary: "Reply approved and sent with rotation instructions.",
    classification: null,
    draftResponse: null,
    resolution: "Reply approved and sent with rotation instructions.",
  },
  {
    id: "demo-8",
    subject: "Contract renewal dispute",
    body: "The renewal quote does not match the terms we agreed with sales. Please escalate this to our account team.",
    status: "escalated",
    priority: "high",
    customerEmail: "marcus@reed.co",
    workflowRunId: null,
    approvalEventId: null,
    createdAt: minutesAgo(360),
    summary: "Escalated to account team for follow-up.",
    classification: null,
    draftResponse: null,
    resolution: "Escalated to account team for follow-up.",
  },
];
