import type { BoardTicket } from "@/types/board";
import { minutesAgo } from "@/utils/minutes-ago";

export const DEMO_TICKETS: BoardTicket[] = [
  {
    id: "demo-1",
    subject: "Cannot access billing settings",
    status: "received",
    priority: "high",
    customerEmail: "maya@acme.com",
    createdAt: minutesAgo(8),
    summary: "Admin sees a permissions error after plan upgrade.",
  },
  {
    id: "demo-2",
    subject: "Invoice export missing rows",
    status: "received",
    priority: "normal",
    customerEmail: "jon@bell.io",
    createdAt: minutesAgo(23),
    summary: "CSV export excludes two team invoices from May.",
  },
  {
    id: "demo-3",
    subject: "Webhook retries are delayed",
    status: "triaging",
    priority: "urgent",
    customerEmail: "priya@shah.dev",
    createdAt: minutesAgo(34),
    summary: "Production integration is waiting on retry delivery.",
  },
  {
    id: "demo-4",
    subject: "Need help changing account owner",
    status: "drafted",
    priority: "low",
    customerEmail: "erik@novak.se",
    createdAt: minutesAgo(62),
    summary: "Requester needs the ownership transfer steps confirmed.",
  },
  {
    id: "demo-5",
    subject: "Data retention concern",
    status: "waiting_for_approval",
    priority: "high",
    customerEmail: "nora@alvarez.com",
    createdAt: minutesAgo(120),
    summary: "Draft response is ready but needs policy review.",
  },
  {
    id: "demo-6",
    subject: "Escalation request for outage report",
    status: "waiting_for_approval",
    priority: "urgent",
    customerEmail: "support@acme.com",
    createdAt: minutesAgo(180),
    summary: "Customer is asking for a formal incident summary.",
  },
  {
    id: "demo-7",
    subject: "API key rotation question",
    status: "resolved",
    priority: "normal",
    customerEmail: "lena@ortiz.mx",
    createdAt: minutesAgo(240),
    summary: "Reply approved and sent with rotation instructions.",
  },
  {
    id: "demo-8",
    subject: "Contract renewal dispute",
    status: "escalated",
    priority: "high",
    customerEmail: "marcus@reed.co",
    createdAt: minutesAgo(360),
    summary: "Escalated to account team for follow-up.",
  },
];
